### ISSUE TITLE
Improve error message when sending a changefeed query to non-query endpoint

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/replicator#720] opened 2024-02-23 21:26 UTC
If a changefeed query payload is sent to a non-query path (i.e. it's missing the table path element), the following error is returned: `json: unknown field "__crdb__"`. We should add a special-case here to suggest the correct course of action if we see the `__crdb__` field.

**Comment by ryanluu12345** [comment] 2024-09-24 16:32
Hi @bobvawter , just to clarify here:
1. When you say that it is missing the table path element, what exactly do you mean? In the example below, do you mean it's missing the `FOR TABLE` or the `defaultdb/public` piece?
```
CREATE CHANGEFEED FOR TABLE public.tbl1 INTO 'webhook-https://localhost:30004/defaultdb/public?insecure_tls_skip_verify=true'
```

2. And for the correct course of action, my understanding is to alert them to include the table path (i.e. the `defaultdb/public` and a generic example. Is this a correct assumption?

**Comment by bobvawter** [comment] 2024-09-24 17:16
A changefeed query must be sent to a path like `/database/schema/table`, since a query doesn't implicitly have a table name.

X-ref: https://github.com/cockroachdb/replicator/wiki/C2C#change-data-capture-queries

**Comment by ryanluu12345** [comment] 2024-09-30 23:20
Reproduction notes (for reference)
1. I was able to verify that when running with this configuration, I'm able to ensure that messages can be sourced from Cockroach changefeeds and applied to non-homogeneous targets:
```
# Replicator run
go run . start --bindAddr 0.0.0.0:30004 --targetConn 'mysql://root:@localhost:3306/molt?sslmode=disable' --stagingConn 'postgres://root@localhost:26257/molt?sslmode=disable' --stagingSchema _replicator --disableAuthentication --tlsSelfSigned -v

# Changefeed config on CRDB source
root@127.0.0.1:26257/molt> CREATE CHANGEFEED                                                                                 
                        -> INTO 'webhook-https://host.docker.internal:30004/molt/tbl1?insecure_tls_skip_verify=true'         
                        -> WITH envelope='wrapped', format='json', diff, updated, resolved='1s',                             
                        -> min_checkpoint_frequency='1s',                                                                    
                        ->      webhook_sink_config='{"Flush":{"Bytes":1048576,"Frequency":"1s"}}'                           
                        -> AS SELECT                                                                                         
                        ->      *                                                                                            
                        -> FROM                                                                                              
                        ->      molt.public.tbl1                                                                             
                        -> ;   
```

2. Then I took away the table parameter and expected to see an error, and ended up seeing an error:
```
root@127.0.0.1:26257/molt> CREATE CHANGEFEED                                                                                 
                        -> INTO 'webhook-https://host.docker.internal:30004/molt?insecure_tls_skip_verify=true'              
                        -> WITH envelope='wrapped', format='json', diff, updated, resolved='1s',                             
                        -> min_checkpoint_frequency='1s',                                                                    
                        ->      webhook_sink_config='{"Flush":{"Bytes":1048576,"Frequency":"1s"}}'                           
                        -> AS SELECT                                                                                         
                        ->      *                                                                                            
                        -> FROM                                                                                              
                        ->      molt.public.tbl1                                                                             
                        -> ;  
```

The error:
```
ERROR  [Sep 30 16:18:34]                                               detail="empty table name\ngithub.com/cockroachdb/replicator/internal/util/ident.ParseTableRelative\n\t/Users/ryanluu/go/src/github.com/cockroachdb/cdc-sink/internal/util/ident/parse.go:158\ngithub.com/cockroachdb/replicator/internal/source/cdc.(*Handler).webhook\n\t/Users/ryanluu/go/src/github.com/cockroachdb/cdc-sink/internal/source/cdc/webhook.go:121\ngithub.com/cockroachdb/replicator/internal/source/cdc.(*Handler).ServeHTTP\n\t/Users/ryanluu/go/src/github.com/cockroachdb/cdc-sink/internal/source/cdc/handler.go:110\ngithub.com/cockroachdb/replicator/internal/util/stdserver.Mux.logWrapper.func2\n\t/Users/ryanluu/go/src/github.com/cockroachdb/cdc-sink/internal/util/stdserver/wrapper.go:105\nnet/http.HandlerFunc.ServeHTTP\n\t/Users/ryanluu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.6.darwin-arm64/src/net/http/server.go:2171\nnet/http.(*ServeMux).ServeHTTP\n\t/Users/ryanluu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.6.darwin-arm64/src/net/http/server.go:2688\ngolang.org/x/net/http2/h2c.h2cHandler.ServeHTTP\n\t/Users/ryanluu/go/pkg/mod/golang.org/x/net@v0.29.0/http2/h2c/h2c.go:125\nnet/http.serverHandler.ServeHTTP\n\t/Users/ryanluu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.6.darwin-arm64/src/net/http/server.go:3142\nnet/http.initALPNRequest.ServeHTTP\n\t/Users/ryanluu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.6.darwin-arm64/src/net/http/server.go:3750\nnet/http.(*http2serverConn).runHandler\n\t/Users/ryanluu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.6.darwin-arm64/src/net/http/h2_bundle.go:6192\nruntime.goexit\n\t/Users/ryanluu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.6.darwin-arm64/src/runtime/asm_arm64.s:1222" error="empty table name" uri=/molt
```

@bobvawter I don't see the `unknown field "__crdb__"` logging here. Wondering if this has since been fixed? Or am I considering the wrong case here? In the example above, I removed the table path and see that it tells me that the table name is empty

**Comment by ryanluu12345** [comment] 2024-09-30 23:36
As a follow up, I tried this for a Cockroach source and a Postgres target as well:
```
root@127.0.0.1:26257/molt> CREATE CHANGEFEED                                            
                        -> INTO                                                         
                        -> 'webhook-https://host.docker.internal:30004/molt/public?insec
                        -> ure_tls_skip_verify=true'                                    
                        -> WITH envelope='wrapped', format='json', diff, updated,       
                        -> resolved='1s', min_checkpoint_frequency='1s',                
                        ->                                                              
                        -> webhook_sink_config='{"Flush":{"Bytes":1048576,"Frequency":"1
                        -> s"}}'                                                        
                        -> AS SELECT                                                    
                        ->      *                                                       
                        -> FROM                                                         
                        ->      molt.public.tbl1                                        
                        -> ;  
```

Then I see this logging again:
```
erverConn).runHandler\n\t/Users/ryanluu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.6.darwin-arm64/src/net/http/h2_bundle.go:6192\nruntime.goexit\n\t/Users/ryanluu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.6.darwin-arm64/src/runtime/asm_arm64.s:1222" error="empty table name" uri=/molt/public
```

**Comment by ryanluu12345** [comment] 2024-10-03 00:03
Hi @bobvawter , wondering if I could get your insight here. I want to make sure I'm reproducing in the manner that you discovered this issue, since it appears the empty table path name seems to already tell me that my table is empty (for multiple dialects for C2X)

**Comment by bobvawter** [comment] 2024-10-03 13:52
This specific behavior has probably changed and this issue might have been fixed with other changes to CDC query parsing. If you change https://github.com/cockroachdb/replicator/blob/1642bdc6d6ae4fd825e4ca07e92e1ce0a4b9c63e/internal/source/cdc/server/integration_test.go#L240 to `pathIdent = target.Schema()` that will run the tests as though the user hadn't specified the entire path.  If the error messages created by doing so point the user in the right direction, feel free to close this out.

**Comment by ryanluu12345** [comment] 2024-10-03 17:29
Thanks for the pointer. For some reason when I run this test with everything configured (I verified I have all databases up properly), I see that it just hangs at this line:
```
{
  "address": {
    "IP": "127.0.0.1",
    "Port": 64913,
    "Zone": ""
  },
  "message": "Server listening",
  "severity": "INFO",
  "timestamp": {
    "seconds": 1727976386,
    "nanos": 869181000
  }
}
```
This ends up timing out at 100 seconds (the VsCode testing timeout), but wondering if you've seen this behavior before. Btw, this is with me setting `pathIdent = target.Schema()`.

When I don't run with a timeout, it just context cancels, so something is obviously blocked.

**Comment by ryanluu12345** [comment] 2024-10-03 19:12
Spoke offline with @bobvawter , the recommendation is to use docker for the source MySQL, PG, and Oracle instances but use a local instance of CRDB for testing purposes.

**Comment by ryanluu12345** [comment] 2024-10-03 23:23
@bobvawter, yep I think that the the logging is clear about why the error occurred. Here is what I found upon searching for error logs when we use just the `table.Schema` and not the full path:
```
{
  "error": "empty table name",
  "severity": "ERROR",
  "timestamp": {
    "seconds": 1727997665,
    "nanos": 656117000
  },
  "uri": "/tgt-71106-38/public"
}
```
It tells the user that the table name was not set. Looking at the URI, it's clear this is the case since we see the DB and schema. I think the next logical step is for them to include the table name here.

Going to close this one out!

**Closed** 2024-10-08 18:13 UTC
Labels: enhancement, good first issue
