### ISSUE TITLE
Rename cdc-sink to Replicator

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/replicator#734] opened 2024-03-02 00:49 UTC
Step one is just to identify all the places where the rename will beak functionality.

**Comment by bobvawter** [comment] 2024-03-02 00:58
The biggest trouble will be getting a new binaries bucket and DockerHub repo.  We could use this as an opportunity to instead host the artifacts and images within the GitHub equivalent.  There's also the matter of this repo being managed via the CRL infrastructure terraform system.

**Comment by bobvawter** [comment] 2024-05-31 20:27
Duplicate of #844

**Closed by bobvawter** 2024-05-31 20:27 UTC
